remote_theme: amitmerchant1990/reverie
title: Bluegrass Dev
description: An unbridled spirit gettin' his nerd on in the Bluegrass.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.bluegrass.dev" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
  ]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# search_enabled: true

# Set the search token separator for hyphenated-word search:
# search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
# heading_anchors: true

# Aux links for the upper right navigation
# aux_links:
  # "Bluegrass Dev on GitHub":
    # - "//github.com/bluegrass-dev"

# Footer content appears at the bottom of every page's main content
# footer_content: 'Copyright &copy; 2020 CJ Taylor. Distributed by an <a href="https://github.com/bluegrass-dev/blog/tree/master/LICENSE.txt">MIT license.</a>'


# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
google_analytics: UA-164583511-1

plugins:
  - jekyll-seo-tag
  - jekyll-twitter-plugin

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Reverie settings 

name: Bluegrass Dev

avatar: /images/covatar.png

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: http://blog.bluegrass.dev
enforce_ssl: https://blog.bluegrass.dev


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# disqus: blog-bluegrass-dev.disqus.com

# Includes an icon in the footer for each username you enter
footer-links:
  email: cj.taylor@bluegrass.dev
  github: cj-taylor
  linkedin: cj-taylor
  rss: rss
  twitter: BluegrassDevCJ
  # stackoverflow: 
  # youtube: # channel/<your_long_string> or user/<user-name>